; PlatformIO Project Configuration File for ESP32-S3 N8R2

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
;upload_speed = 115200

;upload_port = /dev/ttyUSB0
;monitor_port = /dev/ttyUSB0

lib_deps =
    scottp/victronble
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

; Utilizing the 8MB Flash (N8)
board_build.partitions = default_8MB.csv

; Configuring 2MB Quad-SPI PSRAM (R2)
board_build.arduino.memory_type = qio_qspi

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    
    ; --- USB CDC Configuration ---
    ; Enable these 2 flags if your S3 board uses its native USB port for Serial logging.
    ; If your board has an external UART chip (CP2102/CH340), keep them commented out.
    ; -D ARDUINO_USB_CDC_ON_BOOT=1
    ; -D ARDUINO_USB_MODE=1